import numpy as np
from itertools import combinations
import math
from math import gcd
import pandas as pd
import matplotlib.pyplot as plt
import time
import pickle

def get_best_q_vectorized(generators, n, chunk_size=50000):
    """
    Evaluates the 'q' metric (minimum maximum distance to the 0 vector mod n) 
    for a list of generators. Uses chunking to prevent out-of-memory errors on large sets.
    """
    if len(generators) == 0:
        return 0, None
        
    generators = np.array(generators, dtype=np.int32)
    best_q = -1
    best_g = None
    
    # c_vals shape: (n-1, 1, 1) to broadcast against (chunk_size, d)
    c_vals = np.arange(1, n, dtype=np.int32).reshape(-1, 1, 1)
    
    for i in range(0, len(generators), chunk_size):
        chunk = generators[i:i + chunk_size]
        
        # Reshape chunk to (1, chunk_size, d)
        g_reshaped = chunk.reshape(1, chunk.shape[0], chunk.shape[1])
        
        # Calculate multiples modulo n
        # Shape: (n-1, chunk_size, d)
        multiples = (c_vals * g_reshaped) % n
        
        # Calculate distance to 0 mod n
        dists = np.minimum(multiples, n - multiples)
        
        # Infinity norm: max across coordinates (axis=2)
        # Shape: (n-1, chunk_size)
        max_dists = np.max(dists, axis=2)
        
        # Minimum non-zero distance across all elements in the subgroup (axis=0)
        # Shape: (chunk_size,)
        qs = np.min(max_dists, axis=0)
        
        # Find the max q in this chunk
        chunk_best_idx = np.argmax(qs)
        chunk_best_q = qs[chunk_best_idx]
        
        if chunk_best_q > best_q:
            best_q = chunk_best_q
            best_g = chunk[chunk_best_idx]
            
    return best_q, best_g

def get_best_q_vectorized_2d_unique(generators, n, p=None, chunk_size=None):
    """
    Evaluates the 'q' metric for pairs of generators.
    Calculates s*gen_1 + t*gen_2 mod p, where s and t range from 0 to n-1.
    
    Args:
        generators: Array-like of shape (N, 2, d) where N is number of pairs,
                    2 represents (gen_1, gen_2), and d is the dimension.
        n: The range for parameters s and t (0 to n-1).
        p: The modulo base. If None, defaults to n.
        chunk_size: Number of generator pairs to process at once.
        
    Returns:
        best_q: The best distance metric found.
        best_g: The generator pair that achieved best_q.
        best_unique_count: The number of unique elements generated by best_g 
                           (unique non-zero elements + 1 for the 0 vector).
    """
    if len(generators) == 0:
        return 0, None, 0
        
    p = p if p is not None else n
    generators = np.array(generators, dtype=np.int32)
    
    if generators.ndim != 3 or generators.shape[1] != 2:
        raise ValueError("Generators must have shape (N, 2, d) representing N pairs of d-dimensional vectors.")
        
    d = generators.shape[2]
    
    # Calculate a safe chunk size to keep RAM usage around ~100-200MB per chunk
    if chunk_size is None:
        chunk_size = max(1, 10_000_000 // ((n**2) * d))
        
    best_q = -1
    best_g = None
    
    # Pre-compute all (s, t) combinations from 0 to n-1
    s = np.arange(n, dtype=np.int32)
    t = np.arange(n, dtype=np.int32)
    S, T = np.meshgrid(s, t, indexing='ij')
    
    # Flatten and remove the (0, 0) case (which is at index 0)
    s_flat = S.ravel()[1:]
    t_flat = T.ravel()[1:]
    
    # Reshape for broadcasting: (V, 1, 1) where V = n**2 - 1
    s_vals = s_flat.reshape(-1, 1, 1)
    t_vals = t_flat.reshape(-1, 1, 1)
    
    for i in range(0, len(generators), chunk_size):
        chunk = generators[i:i + chunk_size]
        
        # Split chunk into g1 and g2 and reshape to (1, chunk_size, d)
        g1 = chunk[:, 0, :].reshape(1, chunk.shape[0], d)
        g2 = chunk[:, 1, :].reshape(1, chunk.shape[0], d)
        
        # Calculate multiples modulo p
        # s_vals * g1 triggers broadcast: (V, 1, 1) * (1, C, d) -> (V, C, d)
        multiples = (s_vals * g1 + t_vals * g2) % p

        # Calculate distance to 0 mod p
        dists = np.minimum(multiples, p - multiples)
        
        # Infinity norm: max across coordinates (axis=2)
        # Shape: (V, chunk_size)
        max_dists = np.max(dists, axis=2)

        # Dispose of 0 vectors: any vector that evaluates to all zeros will have a max distance of 0.
        # Set these to `p` (a value > max possible distance of p//2) so `np.min` ignores them.
        max_dists[max_dists == 0] = p

        # Minimum non-zero distance across all elements in the subgroup (axis=0)
        qs = np.min(max_dists, axis=0)
        
        # If a generator pair produced *only* zero vectors, its min distance will evaluate to `p`. 
        # We catch these and reset their actual q metric back to 0.
        qs[qs == p] = 0
        
        # Find the max q in this chunk
        chunk_best_idx = np.argmax(qs)
        chunk_best_q = qs[chunk_best_idx]
        
        if chunk_best_q > best_q:
            best_q = chunk_best_q
            best_g = chunk[chunk_best_idx]
            
    # Calculate unique elements for the absolute best generator pair
    best_unique_count = 0
    if best_g is not None:
        # Generate the full subspace including (s=0, t=0)
        s_all = S.ravel().reshape(-1, 1)
        t_all = T.ravel().reshape(-1, 1)
        
        g1_best = best_g[0].reshape(1, d)
        g2_best = best_g[1].reshape(1, d)
        
        all_multiples = (s_all * g1_best + t_all * g2_best) % p
        
        # Filter down to the unique vectors generated by this pair
        unique_elements = np.unique(all_multiples, axis=0)
        
        # Dispose of the all-zero vector from the unique set
        non_zero_unique = unique_elements[np.any(unique_elements != 0, axis=1)]
        
        # Final count: number of unique non-zero elements + 1 (for the 0 vector)
        best_unique_count = len(non_zero_unique) + 1
            
    return best_q, best_g, best_unique_count

def is_pairwise_coprime(tup):
    for i in range(len(tup)):
        for j in range(i + 1, len(tup)):
            if gcd(tup[i], tup[j]) > 1:
                return False
    return True

def generate_optimal_lattices(d_min, d_max, p_min, p_max):
    results = {
        'S': [], 'T': [], 'T_coprime': [], 'T_gcd': [], 'U_1': [], 'U_2': [], 'U_3': []
    }
    time_elapsed = np.zeros(7, dtype=np.float64)
    
    for d in range(d_min, d_max + 1):
        n_min = math.floor(p_min ** d)
        n_max = math.floor(p_max ** d)
        # n_min_u3 = math.floor(p_min ** (d / 2))
        # n_max_u3 = math.floor(p_max ** (d / 2))
        
        print(f"\n--- Dimension {d} | n_range: [{n_min}, {n_max}] ---")
        
        for n in range(n_min, n_max + 1):
            max_k = n // 2
            
            # ==========================================
            # 1. S Type
            # ==========================================
            s_generators = []
            for k in range(2, max_k + 1):
                vec = [(k ** i) % n for i in range(d)]
                s_generators.append(vec)
            time_start = time.time()
            q_s, best_s = get_best_q_vectorized(s_generators, n)
            time_elapsed[0] += time.time() - time_start
            results['S'].append((n, d, q_s, best_s, n))
            
            # ==========================================
            # 2. T Types (T, T_coprime, T_gcd)
            # ==========================================
            t_generators = []
            t_coprime_generators = []
            t_gcd_generators = []
            
            for k_comb in combinations(range(2, max_k + 1), d - 1):
                vec = [1] + list(k_comb)
                t_generators.append(vec)
                
                if is_pairwise_coprime(vec):
                    t_coprime_generators.append(vec)
                    
                if all(gcd(k, n) == 1 for k in k_comb):
                    t_gcd_generators.append(vec)
                    
            time_start = time.time()
            q_t, best_t = get_best_q_vectorized(t_generators, n)
            time_elapsed[1] += time.time() - time_start
            time_start = time.time()
            q_t_coprime, best_t_coprime = get_best_q_vectorized(t_coprime_generators, n)
            time_elapsed[2] += time.time() - time_start
            time_start = time.time()
            q_t_gcd, best_t_gcd = get_best_q_vectorized(t_gcd_generators, n)
            time_elapsed[3] += time.time() - time_start
            
            results['T'].append((n, d, q_t, best_t, n))
            results['T_coprime'].append((n, d, q_t_coprime, best_t_coprime, n))
            results['T_gcd'].append((n, d, q_t_gcd, best_t_gcd, n))
            
            # ==========================================
            # 3. U Types (U_1, U_2)
            # ==========================================
            u1_generators = []
            u2_generators = []
            
            # U_1: s=t -> s*g1 + s*g2 -> g = (g1 + g2) mod n
            # U_2: s+t=n -> t = -s -> s*g1 - s*g2 -> g = (g1 - g2) mod n
            for k1, k2 in combinations(range(2, max_k + 1), 2):
                g1 = np.array([(k1 ** i) % n for i in range(d)])
                g2 = np.array([(k2 ** i) % n for i in range(d)])
                
                u1_generators.append((g1 + g2) % n)
                u2_generators.append((g1 - g2) % n)
                
            time_start = time.time()
            q_u1, best_u1 = get_best_q_vectorized(u1_generators, n)
            time_elapsed[4] += time.time() - time_start
            time_start = time.time()
            q_u2, best_u2 = get_best_q_vectorized(u2_generators, n)
            time_elapsed[5] += time.time() - time_start
            
            results['U_1'].append((n, d, q_u1, best_u1, n))
            results['U_2'].append((n, d, q_u2, best_u2, n))
            
            print(f"Processed n={n} | Best q values -> S:{q_s}, T:{q_t}, T_cop:{q_t_coprime}, T_gcd:{q_t_gcd}, U1:{q_u1}, U2:{q_u2}")

        for n in range(n_min, n_max + 1):
            max_k = n // 2
            
            # ==========================================
            # 4. U_3 Type
            # ==========================================
            u3_generators = []
            
            for k1, k2 in combinations(range(2, max_k + 1), 2):
                g1 = np.array([(k1 ** i) % n for i in range(d)])
                g2 = np.array([(k2 ** i) % n for i in range(d)])
                
                u3_generators.append([g1,g2])
                
            time_start = time.time()
            q_u3, best_u3, best_number_u3 = get_best_q_vectorized_2d_unique(u3_generators, n)
            time_elapsed[6] += time.time() - time_start
            
            results['U_3'].append((n, d, q_u3, best_u3, best_number_u3))
            
            print(f"Processed n={n} | Best q value for U_3: {q_u3} with {best_number_u3} unique elements")

    return results, time_elapsed

def theta(p,q):
    summ = 0
    for i in range(q):
        multi = 1
        for j in range(1,q):
            c_i = math.cos(2*math.pi*i/q)
            a_j = math.cos(2*math.pi/p*math.floor(j*p/q))
            multi = multi*(c_i-a_j)/(1-a_j)
        summ = summ + multi
    return summ*p/q

if __name__ == "__main__":
    # Example execution: Customize these bounds based on your memory/compute limits
    D_MIN = 2
    D_MAX = 5
    P_MIN = 2
    P_MAX = 3
    
    start_time = time.time()

    final_data, time_elapsed = generate_optimal_lattices(D_MIN, D_MAX, P_MIN, P_MAX)

    results = {
        "final_data": final_data,
        "time_elapsed": time_elapsed
    }

    with open("results.pkl", "wb") as f:
        pickle.dump(results, f)
    print(f"Time elapsed: {time.time() - start_time:.2f} seconds")
    print("Time elapsed per generator type:")
    for i, (gen_type, elapsed) in enumerate(zip(['S', 'T', 'T_coprime', 'T_gcd', 'U_1', 'U_2', 'U_3'], time_elapsed)):
        print(f"  {gen_type}: {elapsed:.2f} seconds")
    # ==========================================
    # 1. CONVERT final_data TO PANDAS DATAFRAME
    # ==========================================
    # (Assuming 'final_data' is already in memory from the previous script)
    rows = []
    for gen_type, results in final_data.items():
        for row in results:
            n, d, q, best_g, best_number = row
            rows.append({
                'type': gen_type,
                'd': d,
                'n': n,
                'q': q,
                'best_n': best_number,
            })

    df = pd.DataFrame(rows)

    # Filter out q=0 to prevent division by zero errors
    df = df[df['q'] > 0].copy()

    # Add the required derived columns for plotting
    df['n_over_q'] = df['n'] / df['q']
    df['n_1_over_d'] = df['best_n'] ** (1 / df['d'])

    # ==========================================
    # 2. FAST PARETO FILTER FUNCTION
    # ==========================================
    def apply_fast_filter(group_df, threshold_col, val_col='n_over_q'):
        """
        1. Sorts by the threshold column descending.
        2. Keeps only rows where n/q is strictly less than the lowest n/q seen so far.
        """
        sorted_df = group_df.sort_values(by=[threshold_col, val_col], ascending=[False, True])
        cummin = sorted_df[val_col].cummin()
        mask = (sorted_df[val_col] == cummin) & (sorted_df[val_col] < cummin.shift(1).fillna(np.inf))
        return sorted_df[mask].sort_values(by=val_col, ascending=True)

    # ==========================================
    # 3. PART 1: FILTER & PLOT PER DIMENSION
    # ==========================================
    filtered_part1_list = []
    types = df['type'].unique()
    dimensions = sorted(df['d'].unique())

    for gen_type in types:
        for d in dimensions:
            mask = (df['type'] == gen_type) & (df['d'] == d)
            subset = df[mask]
            if subset.empty:
                continue
                
            filtered_sub = apply_fast_filter(subset, threshold_col='n', val_col='n_over_q')
            filtered_part1_list.append(filtered_sub)

    if filtered_part1_list:
        df_filtered_part1 = pd.concat(filtered_part1_list, ignore_index=True)
    else:
        df_filtered_part1 = pd.DataFrame(columns=df.columns)

    #Get lovasz theta function for plotting upper bound
    t = np.linspace(P_MIN, P_MAX, 100*(P_MAX-P_MIN)+1)
    theta_n = np.zeros(100*(P_MAX-P_MIN)+1)
    for i in range(100*(P_MAX-P_MIN)+1):
        theta_n[i] = theta(int(t[i]*100),100)

    # Plotting Part 1
    for gen_type in types:
        subset_type = df_filtered_part1[df_filtered_part1['type'] == gen_type]
        if subset_type.empty:
            continue
            
        plt.figure(figsize=(10, 6))
        for d in dimensions:
            subset_d = subset_type[subset_type['d'] == d]
            if not subset_d.empty:
                plt.step(subset_d['n_over_q'], subset_d['n_1_over_d'], 
                        where='post', label=f'd = {d}', marker='o', markersize=4)
                #if gen_type == 'U_3':
                #    print(subset_d['n_over_q'], subset_d['n_1_over_d'])

        plt.plot(t, theta_n, 'r--', linewidth=2, label='Lovász theta')
        plt.title(f'Filtered Set for Generator Type: {gen_type}\n(Filtered by n per dimension)')
        plt.xlabel('n / q')
        plt.ylabel('n ** (1/d)')
        plt.xlim(P_MIN, P_MAX)
        plt.ylim(P_MIN, P_MAX)
        plt.legend(title='Dimension')
        #plt.grid(True, linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.show()

    # ==========================================
    # 4. PART 2: FILTER & PLOT ACROSS ALL DIMENSIONS
    # ==========================================
    filtered_part2_list = []

    for gen_type in types:
        subset = df[df['type'] == gen_type]
        if subset.empty:
            continue
        
        filtered_sub = apply_fast_filter(subset, threshold_col='n_1_over_d', val_col='n_over_q')
        filtered_part2_list.append(filtered_sub)

    if filtered_part2_list:
        df_filtered_part2 = pd.concat(filtered_part2_list, ignore_index=True)
    else:
        df_filtered_part2 = pd.DataFrame(columns=df.columns)

    # Plotting Part 2
    plt.figure(figsize=(10, 6))

    markers = ['s','D','o', '^', 'v', '>', '<', 'p', '*', 'h']  # Extend as needed
    for gen_type in types:
        subset_type = df_filtered_part2[df_filtered_part2['type'] == gen_type]
        if not subset_type.empty:
            plt.step(subset_type['n_over_q'], subset_type['n_1_over_d'], 
                    where='post', label=f'{gen_type}', marker=markers[types.tolist().index(gen_type)], markersize=8-0.5*types.tolist().index(gen_type))

    plt.plot(t, theta_n, 'r--', linewidth=2, label='Lovász theta')
    plt.title('Filtered Set for All Generator Types\n(Filtered by n**(1/d) across all dimensions)')
    plt.xlabel('n / q')
    plt.ylabel('n ** (1/d)')
    plt.xlim(P_MIN, P_MAX)
    plt.ylim(P_MIN, P_MAX)
    plt.legend(title='Generator Type')
    #plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()